name = "EnergyDefect"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["EnergyDefect"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0"

[[lean_lib]]
name = "EnergyDefect"
